### ISSUE TITLE
Support Coremedia 10 - Version 2001.1/2001.2

### ISSUE THREAD

**Issue by mlauke** [tallence/core-redirects#36]
hi,

not really an issue but just a question regarding cm 10 support. is it planned for near future? and if so, can u tell a potential release date? otherwise we'll fork it and maybe can contribute the working version.

kind regards

**Comment by NicholasFechner** [comment]
Hi,
we're currently working on an update to 2001. Should be done sometime next week. So if you have enough time, you could wait until we relase the update.

Nicholas

**Comment by mlauke** [comment]
great to hear that. many thanks

**Comment by chris21a** [comment]
I would also like to try the new version.Looking forward.

**Comment by asique57** [comment]
Is there any update on this?

**Comment by NicholasFechner** [comment]
Unfortunately, we ran into some Studio troubles during the update (who would have thought....) and our Studio crack @TallenceJanHendrikPopp is still on holidays. Might be a week or two late. Sorry...

**Comment by NicholasFechner** [comment]
We're going to keep this issue open until fixed, so you can get a notification, when we are done.

**Comment by mlauke** [comment]
many thx!

**Comment by TallenceJanHendrikPopp** [comment]
New version compatible with 2004.2 (https://github.com/tallence/core-redirects)
