### ISSUE TITLE
Changing redirects causing to invalid plainRedirects and patternRedirects maps

### ISSUE THREAD

**Issue by amorgenthal** [tallence/core-redirects#64]
Hi,

when I edit an existing Redirect document and change only the source URL, the plainRedirects and patternRedirects maps in com.tallence.core.redirects.cae.service.SiteRedirects gets invalid. After com.tallence.core.redirects.cae.service.SiteRedirects#addRedirect the map contains an old empty entry.

Maybe you can solve it by remove those entries:
```
patternRedirects.get(key).add(redirect);
/*Fix*/
patternRedirects.entrySet().removeIf(e -> e.getValue().isEmpty());
```

**Comment by amorgenthal** [comment]
Additinally, when I change the type from plain to regex or reverse, an old entry remains in the opposite map.

**Comment by timolemke** [comment]
Hi @amorgenthal 
on your first point: I agree with you that it would be nicer to remove the entry if the value is an empty List. But is it a bug? The `RedirectMatchingServiceImpl` should not return a redirect in that case.

on your 2nd point: you are right: if the type changes, the old redirect will remain in the wrong map. That's a bug. Thanks for reporting!

**Comment by amorgenthal** [comment]
Hi @timolemke ,

I think the first point is a bug. Example: 
I have a regex Redirect document with the pattern "/abc/(.*)" and I changed it to "/abc/def/(.*)", no redirect is found although it should be. The problem is that the first (outdated) empty map entry is found and not the second with the newly configured redirect. 

The map then contains patterns that no longer represent the state in the CMS, which leads to misbehaviour in redirect management.

**Comment by timolemke** [comment]
@amorgenthal  WIP state in the linked commit.
A unit test is still missing and I still haven't tested it enough,
Can you already verify the fix? Does it work for you?

**Comment by amorgenthal** [comment]
Hello @timolemke ,

first of all: Many thanks for the quick solution!
The solution looks good so far. 
There is one edge case that could cause problems:
If the user enters a invalid regex, the map is not updated because the catch block is executed.
