### ISSUE TITLE
Redirect Manager with Identity Provider?

### ISSUE THREAD

**Issue by UlrikeHeidler** [tallence/core-redirects#69]
Aloha Tallence team,

One of our customers can use the redirect manager on their sandbox, where they use "internal users". However, when they deploy it to UAT, the redirect manager is available, but all buttons are grayed out.

I looked into the console and saw that he is trying to authenticate with a coremedia:///cap/user/ instead of coremedia:///cap/user/123

![image](https://github.com/tallence/core-redirects/assets/8627964/8f4a40ea-abb9-40f9-9998-d334850c4a9c)

We are using a cognito-authentication in UAT and Prod. The administrative user group for this should be "admininistrator@cognito" instead of admininistratoren. Can I configure this group somewhere?

Are you aware of CMCC Service setups with your extension?

Best, Uli

Ulrike Heidler 
VP of Customer Growth

E-Mail: ulrike.heidler@coremedia.com

**Comment by dfolgner** [comment]
Hey Ulli,

you can set 2 administrative groups:

1. core.redirects.permissions.targetUrlGroup
2. core.redirects.permissions.regexGroup

Yet, I don't think defining any of these groups will solve the problem, as the fallback is com.coremedia.cap.user#isAdministrative 

Is there any corresponding server log from com.tallence.core.redirects.studio.service.RedirectPermissionServiceImpl.java?

**Comment by UlrikeHeidler** [comment]
Aloha @dfolgner :-),
Yes, the two groups are not the problem. The core issue seems to be the resolution of the user permissions. 
Since this only happens in a system that is connected to an SSO in our Cloud, it's really hard to debug. However, I think the culprit is somewhere here:
![image](https://github.com/tallence/core-redirects/assets/8627964/68da9b9a-7963-48d9-9a9a-55939e38d573)
I assume that this path is not properly resolving the user in this scenario. I think we should stick closer to: https://documentation.coremedia.com/cmcc-11/artifacts/2204/webhelp/studio-developer-en/content/SecuritySSO.html. I don't have any other issues with my user on that environment (e.g., for publication or other elevated rights functions). 

Let me check the log files for the output!

Best, Uli

**Comment by jsiewert** [comment]
Hi Ulli,
the new Branch `sso-compatibility-fix` (https://github.com/tallence/core-redirects/tree/sso-compatibility-fix) contains a possible fix for this problem. Since we are not able to test a setup with Cognito, it's not clear if this works. Could you test it in your setup an report back to us? That would be great! :)
Thanks
Jan-Niklas

**Comment by UlrikeHeidler** [comment]
Aloha @jsiewert ,
Thanks for your efforts! I will try. Give me a few days - I'll get back to you ASAP!

Best, Uli

**Comment by UlrikeHeidler** [comment]
Aloha @jsiewert, @dfolgner, and the rest of the Tallence team,
I can confirm that your fix worked! Thank you so much for your help! We can now successfully use your awesome Redirect Manager on higher CMCC Service environments. 
I really appreciate your help!
Best regards, Uli
